@startuml
actor user
user -> client: start working
client -> auth: login

box "Auth"
participant auth
participant cache
end box

auth -> cache: save(key = token, value = user's information)
auth -> client: return token
client -> auth: send request with token
auth -> cache: retrieve user's information by token
cache -> auth: return user's information
auth -> server: process user's request
server -> client: return response

client -> user: view the result
@enduml