openapi: "3.0.3"
info:
  title: Simple API overview
  version: 1.0.0
  description: A simple API to operate house

servers:
  - url: http://localhost:8080/api/v1

paths:
  /house/{id}:
    get:
      description: return a house
      tags:
        - house
      parameters:
        - in: header
          name: x-user-id
          required: true
          schema:
            $ref: "#/components/headers/x-user-id"
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/houseResponse"
  /house:
    get:
      description: return a list of house
      parameters:
        - in: header
          name: x-user-id
          required: true
          schema:
            $ref: "#/components/headers/x-user-id"
        - name: limit
          in: query
          description: Limits the number of items
          schema:
            type: integer
        - in: header
          name: AuthToken
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/houseResponse"
      tags:
        - house
    put:
      description: upsert data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/houseRequest"
      responses:
        "204":
          description: Success
      tags:
        - Internal

security:
  - AuthToken: []

components:
  securitySchemes:
    AuthToken:
      type: http
      scheme: bearer

  schemas:
    houseResponse:
      type: object
      properties:
        id:
          type: integer
          description: id
        shape:
          type: string
          description: shape
    houseRequest:
      type: object
      properties:
        name:
          type: string
  headers:
    x-user-id:
      schema:
        type: string
      required: true
      example: "abcdef"
